owner: Clipdrop
repo: clipdrop-upptime

sites:
  # Clipdrop web
  - name: Clipdrop web home page
    url: https://clipdrop.co
    maxResponseTime: 1000
    assignees:
      - ieschalier
    icon: https://raw.githubusercontent.com/initml/clipdrop-upptime/master/assets/clipdrop-favicon.ico
  - name: Clipdrop web remove background tool
    url: https://clipdrop.co/remove-background
    maxResponseTime: 1000
    assignees:
      - ieschalier
    icon: https://raw.githubusercontent.com/initml/clipdrop-upptime/master/assets/clipdrop-favicon.ico
  - name: Clipdrop web image upscaler tool
    url: https://clipdrop.co/image-upscaler
    maxResponseTime: 1000
    assignees:
      - ieschalier
    icon: https://raw.githubusercontent.com/initml/clipdrop-upptime/master/assets/clipdrop-favicon.ico
  - name: Clipdrop web cleanup
    url: https://cleanup.pictures
    maxResponseTime: 1000
    assignees:
      - ieschalier
    icon: https://raw.githubusercontent.com/initml/clipdrop-upptime/master/assets/clipdrop-favicon.ico

  # API endpoints
  - name: Remove background API v1
    url: https://apis.clipdrop.co/remove-background/v1/$APIS_HEALTH_METHOD
    maxResponseTime: 1000
    assignees:
      - initml
      - jblanche
    icon: https://raw.githubusercontent.com/initml/clipdrop-upptime/master/assets/clipdrop-favicon.ico
  - name: Cleanup API v1
    url: https://apis.clipdrop.co/cleanup/v1/$APIS_HEALTH_METHOD
    maxResponseTime: 1000
    assignees:
      - initml
      - jblanche
    icon: https://raw.githubusercontent.com/initml/clipdrop-upptime/master/assets/clipdrop-favicon.ico
  - name: Super resolution API v1
    url: https://apis.clipdrop.co/super-resolution/v1/$APIS_HEALTH_METHOD
    maxResponseTime: 1000
    assignees:
      - initml
      - jblanche
    icon: https://raw.githubusercontent.com/initml/clipdrop-upptime/master/assets/clipdrop-favicon.ico

workflowSchedule:
  graphs: "0 * * * *"
  responseTime: "0 * * * *"
  staticSite: "0 * * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/10 * * * *"

status-website:
  cname: status.clipdrop.co
  baseUrl: /clipdrop-upptime
  name: Clipdrop services status
  introTitle: "Clipdrop services status"
  theme: night
  logoUrl: https://raw.githubusercontent.com/initml/clipdrop-upptime/master/assets/clipdrop-icon.svg
  navbar:
    - title: Services status
      href: /
    - title: Clipdrop web
      href: https://clipdrop.co
    - title: Clipdrop APIs
      href: https://clipdrop.co/apis
